# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2


# `run-as:`: Optional sequence. Available to Linux users only. Specifies a Linux user that runs commands in this buildspec file. run-as grants the specified user read and run permissions. When you specify run-as at the top of the buildspec file, it applies globally to all commands. If you don't want to specify a user for all buildspec file commands, you can specify one for commands in a phase by using run-as in one of the phases blocks. If run-as is not specified, then all commands run as the root user.
# run-as: root

# `env:`: Optional sequence. Represents information for one or more custom environment variables.
env:
  # `env/shell`: Optional sequence. Specifies the supported shell for Linux or Windows operating systems.  For Linux, supported shell tags are:
  #   - bash
  #   - /bin/sh
  shell: bash

  # `env/variables`: Required if env is specified, and you want to define custom environment variables in plain text. Contains a mapping of key/value scalars, where each mapping represents a single custom environment variable in plain text
  #variables:
  #  key: "value"
  #  key: "value"
  #parameter-store:
  #  key: "value"
  #  key: "value"
  #exported-variables:
  #  - variable
  #  - variable
  #secrets-manager:
  #  key: secret-id:json-key:version-stage:version-id
  #git-credential-helper: no | yes

#batch:
  #fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:
        
phases:
  install:
    #run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - git clone https://github.com/pwighton/neurodocker.git
      - cd neurodocker
      - git checkout 20210226-fs-source
      - conda create -n nd-dev python=3.8
      - conda activate nd-dev
      - python -m pip install --no-cache-dir --editable .[all]
    #finally:
    #  - command
  #pre_build:
    #run-as: Linux-user-name
    #on-failure: ABORT
    #commands:
    #finally:

  build:
    #run-as: Linux-user-name
    on-failure: ABORT
    commands:
      - neurodocker generate docker --base-image ubuntu:xenial --pkg-manager apt --yes --freesurfer license_base64=cGF1bEBjb3J0aWNvbWV0cmljcy5jb20KMzA0NDQKICpDZ3lrR3o2bnNYaGcKIEZTVXQweHY5UmlGcWMK method=source repo=https://github.com/pwighton/freesurfer.git version=dev | docker build --no-cache -t pwighton/dev-20210426 -

#  post_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format

